Clean up and update spb-task-03
CSBiology/BIO-BTE-12-V-4 pull request #22
Opened 2022-04-25 12:53 UTC by Freymaurer

2022-04-26 07:19 UTC, kMutagene requested changes

2022-04-26 07:19 UTC, kMutagene commented on notebooks/english/spb-task-03-eng.ipynb
>      "Declare a function that takes a parameter `x` of type `float`. It shall return the value if `x` is greater than zero. If that is not the case, it shall return the value with the \n",
More concise Wording: which value should be returned? Better: "It shall return x if x is.." or "it shall return the value of x if x is ..."

2022-04-26 07:19 UTC, kMutagene commented on notebooks/english/spb-task-03-eng.ipynb
> +    "Declare a function that gets a year as parameter. If it is a leap year, the result shall be `true` else `false`.\n",
More concise instruction: year as datetime or integer?

2022-04-26 07:19 UTC, kMutagene commented on notebooks/english/spb-task-03-eng.ipynb
>      "UnionCase definition `Month` is given:\n",
Move the union case into the code cell

2022-04-26 07:19 UTC, kMutagene commented on notebooks/english/spb-task-03-eng.ipynb
>      "Declare a function that gets parameter `n` of type `int`.  \n",
Type: `a` parameter

2022-04-26 07:19 UTC, kMutagene commented on notebooks/english/spb-task-03-eng.ipynb
>      "Declare a function that gets parameter `n` of type `int`.  \n",
Same typo

2022-04-26 07:19 UTC, kMutagene commented on notebooks/english/spb-task-03-eng.ipynb
>      "The function shall save all numbers from 1 to n in a list.  \n",
Concise instructions: values are not saved in a list. better: "the function shall return a list containing the values from 1 to n"

2022-04-26 07:19 UTC, kMutagene commented on notebooks/english/spb-task-03-eng.ipynb
> +    "The function should apply `f` to all integers from 1 to n and store them in a in a list. \n",
same as above

2022-04-26 07:19 UTC, kMutagene commented on notebooks/german/spb-task-03-de.ipynb
>      "Deklariere eine Funktion, die eine Jahreszahl als Parameter bekommt. Wenn es sich um ein Schaltjahr handelt, soll das Ergebnis `true` sein, andernfalls `false`.  \n",
Here, hint if the date is an integer as well (see english notebook comment)

2022-04-26 07:19 UTC, kMutagene commented on notebooks/german/spb-task-03-de.ipynb
>      "```fsharp\n",
Move union case into code cell

2022-04-26 07:19 UTC, kMutagene commented on notebooks/german/spb-task-03-de.ipynb
> +    "Die Funktion soll alle ganzen Zahlen von 1 bis n in einer Liste speichern.\n",
see english notebook comment

2022-04-26 07:19 UTC, kMutagene commented on notebooks/german/spb-task-03-de.ipynb
>      "Die Funktion soll `f` auf alle ganzen Zahlen von 1 bis n anwenden und in einer in einer Liste speichern.  \n",
see english notebook comment

2022-04-26 07:19 UTC, kMutagene commented on notebooks/german/spb-task-03-de.ipynb
>      "Modifiziere die folgende Funktion (bekannt aus der Vorlesung) so, dass sie -1 zurueckgibt, falls abzusehen ist, dass das Ergebnis groesser als 1000 wird.  \n",
For these code blocks it is okay that they are in the markdown cell, because in contrast to the union case which should be used as-is, they need to be adapted.

2022-04-26 07:56 UTC, Freymaurer commented on notebooks/english/spb-task-03-eng.ipynb
>      "Declare a function that gets parameter `n` of type `int`.  \n",
I don't really get what this means. Do you mean parameter of type `a`, parameter called `a` instead of `n`?

2022-04-26 08:00 UTC, kMutagene commented on notebooks/english/spb-task-03-eng.ipynb
>      "Declare a function that gets parameter `n` of type `int`.  \n",
Declare a function that gets parameter -> Declare a function that gets *a* parameter (add article)

2022-04-27 13:25 UTC, kMutagene requested changes

2022-04-27 13:25 UTC, kMutagene commented on notebooks/english/spb-task-03-eng.ipynb
> +    "Declare a function that gets a parameter `n` of type `int` and a parameter `f` with signature `(int -> int)`. The function should should apply `f` to all integers from 1 to ``n`` and then return
same

2022-04-27 13:25 UTC, kMutagene commented on notebooks/german/spb-task-03-de.ipynb
> +    "Deklariere eine Funktion, die einen Parameter `x` vom Typ ``float`` erhaelt. Ist der Wert von `x` groesser Null, soll die Funktion `x` zurückgeben, falls nicht soll das \n",
same

2022-04-27 13:51 UTC, merged